version: "3"
services:
  db:
    image: mariadb:10.3
    container_name: mariadb
    environment:
      - MYSQL_USER=ironman
      - MYSQL_PASSWORD=secretLocalPassword
      - MYSQL_DATABASE=logbook
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306
